name: CI/CD for NorrisQuote Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup PHP environment with Composer and Xdebug enabled
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          coverage: xdebug

      # Step 3: Set Xdebug environment variable to enable coverage mode
      - name: Set XDEBUG_MODE
        run: echo "XDEBUG_MODE=coverage" >> $GITHUB_ENV

      # Step 4: Install Composer dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Step 5: Run PHPUnit tests and generate coverage report
      - name: Run tests with PHPUnit
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --configuration phpunit.xml

      # Step 6: Check code coverage and add annotation
      - name: Check code coverage
        run: |
          COVERAGE=$(grep -oPm1 "(?<=<metrics statements=)[^>]*" coverage.xml | awk '{print int($1)}')
          if [ "$COVERAGE" -lt 80 ]; then
            echo "::warning ::Code coverage is below 80%: ${COVERAGE}%"
          else
            echo "Code coverage is satisfactory: ${COVERAGE}%"
          fi
